### ISSUE TITLE
Is there any processing done to the table data and the original data in NeuS paper?

### ISSUE THREAD

**Issue by ZZy129326999** [AndreeaDogaru/SphereGuided#1]
Hello, really an excellent work! I received a lot of inspiration. I would like to consult, is there any processing done to the table2 data compared with the original data in NeuS paper? Or some optimization methods. 
![image](https://github.com/AndreeaDogaru/SphereGuided/assets/72543018/e5931f99-e7e6-4928-a3e8-3005c4bc3fdc)
![image](https://github.com/AndreeaDogaru/SphereGuided/assets/72543018/50cf020c-677a-4217-8d29-f6828d80dbdb)
Thank you very much!!

**Comment by AndreeaDogaru** [comment]
Hello, thank you for your interest in our work!
Yes, as mentioned in section 4.4 of our paper, different from previous works, we use the same dilation radius of 12 of the segmentation masks for post-filtering of the meshes in all methods before calculating the metrics. In their papers, NeuS uses a dilation factor of 50, while NeuralWarp uses 12.

**Comment by ZZy129326999** [comment]
> Hello, thank you for your interest in our work! Yes, as mentioned in section 4.4 of our paper, different from previous works, we use the same dilation radius of 12 of the segmentation masks for post-filtering of the meshes in all methods before calculating the metrics. In their papers, NeuS uses a dilation factor of 50, while NeuralWarp uses 12.

Thank your perfect reply!! I will take a good look at your paper again! Learn the details!！

Excuse me, the mesh I exported using instant+Neus is always killed when using the eval script. Could you give me a direction to think about? I want to speed up my program and add some features for comparison. Does this have anything to do with .obj? I also have removed the mesh in the background part.
The script used is the python version of evaluation.  Thank you very much!

**[1]    15036 killed     python evaluation/eval_dtu.py --data_dir  --mesh_path  --scene 110**
![image](https://github.com/AndreeaDogaru/SphereGuided/assets/72543018/949838e6-94e3-4b12-a825-ce35b5d32c83)

**Comment by AndreeaDogaru** [comment]
We only used the script with meshes reconstructed by the models in this repo. Make sure that your mesh is exported on the correct scale.
