### ISSUE TITLE
No permission to access Google Drive files

### ISSUE THREAD

**Issue by trebladev** [AndreeaDogaru/SphereGuided#3]
Hi，
    Thanks for your amazing work.
    When I try to download datasets form link whick in README.md. But it told me that I don't have permission to access it.
    Can you gave me the permission?
Thanks

**Comment by AndreeaDogaru** [comment]
Hi,
Thank you for your interest in our work.
I've updated the NeuS [data download link](https://www.dropbox.com/sh/w0y8bbdmxzik3uk/AAAaZffBiJevxQzRskoOYcyja?dl=0) in `README.md`.
Sorry for the inconvenience.
